### ISSUE TITLE
SSR story

### ISSUE THREAD

**Issue by ctrlplusb** [kentcdodds/glamorous#3]
Hey Kent!

Thanks for adding to CSS-in-JS fatigue with another worthwhile entry! 😜

It looks really great, and I am looking forward to giving it a try.  One question though, have you considered the server side rendering workflow yet?

**Comment by kentcdodds** [comment]
Hi! I haven't thought much about it. I don't personally have a use case. But I'm pretty sure the normal glamor  SSR workflow should work fine. Could you give it a shot? If it does work, would you like to add something to the docs?

**Comment by kentcdodds** [comment]
Yeah, this totally works. Just tried it with my personal site which is server generated and was already using glamor for some styles. Check [this](https://github.com/kentcdodds/kentcdodds.com/commit/e79d8bc1d03dcd7ece27a658ec8b5c6e55210f6b) out. Like magic. I'll add something to the README :)

**Comment by ctrlplusb** [comment]
Zing! Thanks for quick follow up.
