### ISSUE TITLE
Document issues with dynamic styled-components

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous#4]
So `styled-components` has [a sweet babel plugin](https://github.com/styled-components/babel-plugin-styled-components) that allows you to do ahead of time compiling of your styled components. This means that you can just compile at dev-time and you don't have to ship the parser. That's pretty sweet because the parser's big and is a bit of a bottleneck. The plugin is even capable of allowing you to continue have dynamic styles like so:

```js
const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  color: ${props => props.primary ? 'white' : 'palevioletred'};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;
```

However, one thing it cannot do for you is allow you to have dynamic parts of your CSS string that would require the parser to parse out. [For example](https://codepen.io/kentcdodds/pen/MpxMge):

```javascript
function verticallySpaceChildren(space) {
  // this stuff requires the parser, but the babel
  // plugin can't get these transpiled, especially
  // if they're in a separate file.
  return `
    & > *:not(:first-child) {
      margin-left: ${space / 2}px;
    }
    & > *:not(:last-child) {
      margin-right: ${space / 2}px;
    }
  `
}

const Container = styled.div`
  display: flex;
  ${verticallySpaceChildren(12)}
`
```

There are a bunch of similar utilities in [styled-components/polished](https://github.com/styled-components/polished) and there's [an additional plugin](https://github.com/styled-components/babel-plugin-polished) you can install to precompile _those_ as well which is pretty sweet!

Unfortunately, I don't feel like it's worth the effort to write a custom babel plugin that works for all dynamic capabilities when glamorous is more straightforward. But if you commit yourself to not doing this level of dynamic stuff, then feel free to keep using styled-components :)

**Comment by philpl** [comment]
@kentcdodds Small note 😄  This example actually seems like something, that we can transpile and use w/o the parser. When adding the `css` helper to the returned value of the function, the output is:

```js
function verticallySpaceChildren(space) {
  return css([[" > *:not(:first-child) {margin-left: ", space / 2, "px;}"], [" > *:not(:last-child) {margin-right: ",space / 2, "px;}"]]);
}

const Container = styled.div.withConfig({
  displayName: "before__Container",
  componentId: "s1qshall-0"
})([[" {display: -webkit-box;display: -webkit-flex;display: -ms-flexbox;display: flex;", verticallySpaceChildren(12),"}"]]);
```

Things we can't do without a parser are:

- Parse dynamic CSS properties and selectors, that need to be prefixed
- Parse dynamically built up template-string-like arguments
- more stuff I'm forgetting...? ^^"

and the likes.

**Comment by kentcdodds** [comment]
Awesome! This is why I documented it in a GitHub issue, because I figured that things would change :) Thanks for the clarification :+1:

**Comment by mqklin** [comment]
@kentcdodds is this and *right-to-left conversion* the only things that differ `glamorous` from `styled-components`?

**Comment by philpl** [comment]
@mqklin wlCurrwntly the biggest difference IMHO is the Babel plugin, which can do some display name and classname optimisations for us, preprocessing and eventually static style extraction. Furthermore we have some more methods like attrs.

So v2 will have more differences, but v1 has indeed only the difference in style definition, to not be too precise here :)

**Comment by mqklin** [comment]
@philpl yeah, I use styled-components v2 in production and very like it. Just wondered why Kent refused styled-components, I read his article on hackernoon and he is saying there that rtl support is the only difference.

**Comment by kentcdodds** [comment]
@mqklin, RTL is not the only difference. I also prefer regular JavaScript objects to css strings. But that's really just a matter of preference. Also, as @philpl mentioned earlier, there are _some_ cases where you cannot forgo the parser even if you use the babel plugin. That limitation concerns me a little bit as it feels a bit like a leaky abstraction. You need to know what's OK and what's not if you're going to use the babel plugin. So I'm happy with glamorous. I'm happy that styled-components exists so folks who like it can use it.

**Comment by mqklin** [comment]
@kentcdodds, thank you for the response! So here is some details that I can't understand now because of my experience (I mean niceties about parser and plugin) :)
