### ISSUE TITLE
Support functions as rule values?

### ISSUE THREAD

**Issue by alex-wilmer** [kentcdodds/glamorous#5]
The way you have dynamic styles currently is having a separate function which returns an object of rules, which makes it hard to compose fragments of rules together that may or may not be dynamic.

Could rules themselves be values or functions that return values?

```
let MyDiv = styled.div({
   color: 'red',
   fontSize: props => props.big ? '20px' : '10px',
})
```

this way individual rules are agnostic to other ones and don't need to be wrapped in a function in case they don't use props.

thoughts?

**Comment by kentcdodds** [comment]
I added [an Example](https://github.com/kentcdodds/glamorous/blob/master/other/EXAMPLES.md) that should hopefully answer your question. I don't plan to support property-specific functions like styled-components because I think it muddies the lines between static and dynamic styles. Let me know what you think!

**Comment by alex-wilmer** [comment]
fair enough! different benefits I suppose. This introduces somewhat annoying ergonomics of writing a static style.. then realizing it needs to be dynamic later on:

```
const MyLink = glamorous.a(
  {
    color: 'blue',
    textDecoration: 'none',
    fontSize: 24,
  }
)

TO:
const MyLink = glamorous.a(
  {
    color: 'blue',
    textDecoration: 'none',
  },
  ({size = 'small'}) => ({
    fontSize: size === 'big' ? 24 : 16,
  })
)
```

vs

```
const MyLink = glamorous.a(
  {
    color: 'blue',
    textDecoration: 'none',
    fontSize: 24,
  }
)

TO:
const MyLink = glamorous.a(
  {
    color: 'blue',
    textDecoration: 'none',
    fontSize: ({size = 'small'}) => size === 'big' ? 24 : 16,
  }
)
```

I won't push you on this 😛  but I am interested why you think "muddying" the line between static and dynamic styles is bad.

**Comment by kentcdodds** [comment]
Good point on the refactoring story! Thanks for that perspective. Still going to hold firm though :)

> I am interested why you think "muddying" the line between static and dynamic styles is bad.

When I tweeted a few code samples while I was developing this, I was surprised by how many people mentioned to me how much they liked the clear separation between dynamic and static styles. After hearing so much about it, it made me pause and consider why that would be so attractive to people. I realized that it's really a feature of the library. I feel like having fewer ways to do the same thing can have a lot of value. Besides, we're optimizing for reading the code, not writing it ;-)

Thanks again for your perspective!

**Comment by browniefed** [comment]
Not trying to bring this back up but what about just a single function. I've read and think splitting them is a cool idea and is separating.
One of my favorite things is just passing a function as the main prop. Yes combining static and dynamic
```
glamorous.css("div", (props) => ({
  
}))
```
Would you consider this as a potential feature, or are you dead set on keeping dynamic/static separate?

**Comment by kentcdodds** [comment]
What I think you meant by that example is:

```js
glamorous.div((props) => ({
  
}))
```

And that's totally possible!!! :tada:

**Comment by kentcdodds** [comment]
And by "possible" I mean, you can do that today, it's supported :)

Also, if you really wanted to do the string thing you had earlier it'd be:

```javascript
glamorous('div')((props) => ({

}))
```

Whatever floats your boat :)

**Comment by browniefed** [comment]
oooh ha I'm a fool, the API is wonderfully flexible! Thanks
