### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by steida** [kentcdodds/glamorous#6]
Maybe I am dumb, but what's wrong with Fela or Styletron?

**Comment by kentcdodds** [comment]
Fela's great. I'll bet it would be a great backend to this project. Styletron doesn't support child-selectors which my use case needs.

I hope that's helpful :)

**Comment by steida** [comment]
Forgive me stupid questions, but what Glamorous has Fela is missing?

**Comment by steida** [comment]
OK, I see. Have you read me article about Este approach? https://medium.com/@steida/css-in-js-the-argument-refined-471c7eb83955

**Comment by steida** [comment]
I think I covered many many issues related to "style props".

**Comment by devinrhode2** [comment]
Would love your thoughts on @steida 's article Kent :)
